site_name: Alex Security Writeups

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight

nav:
  - Home: index.md
  - Writeups:
      - Hack The Box: hackthebox/example.md
      - TryHackMe: tryhackme/index.md
  - Notes: notes/index.md
  - Tools: tools/index.md

plugins:
  - search
